pipeline:
  # restore-cache:
  #   image: plugins/s3-cache:1
  #   pull: true
  #   restore: true
  #   secrets: [ aws_access_key_id, aws_secret_access_key ]
  #   root: publici-drone/
  #   mount:
  #     - ./.yarn-cache
  #     - ./node_modules

  install:
    image: node:10.13-alpine
    commands:
      - yarn config set cache-folder .yarn-cache
      - yarn install --pure-lockfile --prod

  bake:
    image: node:10.13-alpine
    environment:
      - HOST=where-money-mattered.apps.fivetwentyseven.com
      - PORT=443
    commands:
      - yarn bake

  push-data:
    image: node:10.13-alpine
    secrets: [aws_access_key_id, aws_secret_access_key]
    commands:
      - yarn push-data
    when:
      branch: [master,preview]

  generate-master:
    image: node:10.13-alpine
    environment:
      - HOST=apps.publicintegrity.org
      - PORT=443
      - NODE_ENV=production
    commands:
      - yarn generate
    when:
      branch: master

  generate-preview:
    image: node:10.13-alpine
    environment:
      - HOST=where-money-mattered.apps.fivetwentyseven.com
      - PORT=443
      - NODE_ENV=production
    commands:
      - yarn generate
    when:
      branch: preview

  push:
    image: node:10.13-alpine
    secrets: [aws_access_key_id, aws_secret_access_key]
    commands:
      - yarn push
    when:
      branch: [master,preview]

  # rebuild-cache:
  #   image: plugins/s3-cache:1
  #   pull: true
  #   rebuild: true
  #   secrets: [ aws_access_key_id, aws_secret_access_key ]
  #   root: publici-drone/
  #   mount:
  #     - ./.yarn-cache
  #     - ./node_modules
  #   when:
  #     branch: master

  # flush-cache:
  #   image: plugins/s3-cache:1
  #   pull: true
  #   secrets: [ aws_access_key_id, aws_secret_access_key ]
  #   root: publici-drone/
  #   flush: true

  slack:
    image: plugins/slack
    secrets: [ slack_webhook ]
    template: >
      {{#success build.status}}
        published https://apps.publicintegrity.org/where-money-mattered/
      {{else}}
        failed publishing https://apps.publicintegrity.org/where-money-mattered/
      {{/success}}
    when:
      branch: [master,preview]
